name = "LightGraphsFlows"
uuid = "2f5eb75a-258c-59e0-affc-f41c55f75335"
authors = ["Mathieu Besan√ßon <mathieu.besancon@gmail.com>"]
version = "0.3.1"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LightGraphs = "1"
MathProgBase = "0.7"
SimpleTraits = "0.9"
julia = "1"

[extras]
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Clp", "Test"]
